spring:
  application:
    name: top-5g-pm-file-sync
  profiles:
    active: ${APP_PROFILE:dev}
  config:
    import:
      - optional:file:./topic_config.yml
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:pm_file_sync}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: ${DB_MAX_POOL_SIZE:20}
      minimum-idle: ${DB_MIN_IDLE:5}
      connection-timeout: ${DB_CONNECTION_TIMEOUT:30000}
      idle-timeout: ${DB_IDLE_TIMEOUT:600000}
      max-lifetime: ${DB_MAX_LIFETIME:1800000}
      connection-test-query: SELECT 1
      validation-timeout: 5000
  jpa:
    hibernate:
      ddl-auto: validate
      dialect: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        jdbc:
          batch_size: ${BATCH_SIZE:1000}
          time_zone: UTC
        cache:
          use_second_level_cache: false
          use_query_cache: false
        flush_mode: COMMIT
        default_batch_fetch_size: 1000

server:
  port: ${APP_PORT:8520}
  servlet:
    context-path: ${APP_CONTEXT_PATH:/api/v1}
  error:
    include-message: always
    include-binding-errors: always
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

logging:
  level:
    com.tejas.pmfilesync5g: ${LOG_LEVEL:INFO}
    org.springframework: ${LOG_LEVEL:INFO}
    org.springframework.kafka: INFO
    org.apache.kafka: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file:
    name: ${LOG_FILE_PATH:/app/logs/top-5g-pm-file-sync.log}
    max-size: ${LOG_MAX_SIZE:100MB}
    max-history: ${LOG_MAX_HISTORY:30}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus,env,configprops
      base-path: /actuator
  endpoint:
    health:
      show-details: always
      show-components: always
    info:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: ${PROMETHEUS_ENABLED:true}
    tags:
      application: ${spring.application.name}
      environment: ${APP_PROFILE}

app:
  kafka:
    consumer:
      threads-per-topic: ${KAFKA_THREADS_PER_TOPIC:4}
      max-poll-records: ${KAFKA_MAX_POLL_RECORDS:500}
      session-timeout-ms: ${KAFKA_SESSION_TIMEOUT_MS:30000}
      auto-commit-interval-ms: ${KAFKA_AUTO_COMMIT_INTERVAL_MS:5000}
    monitoring:
      enabled: ${KAFKA_MONITORING_ENABLED:true}
      health-check-interval: ${KAFKA_HEALTH_CHECK_INTERVAL:30000}
    error-handling:
      max-retries: ${KAFKA_MAX_RETRIES:3}
      retry-backoff-ms: ${KAFKA_RETRY_BACKOFF_MS:1000}
