server:
  port: ${APP_PORT:8520}
  servlet:
    context-path: ${APP_CONTEXT_PATH:/api/v1}

spring:
  application:
    name: top-5g-pm-file-sync
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      security.protocol: ${KAFKA_SECURITY_PROTOCOL:PLAINTEXT}
      sasl.mechanism: ${KAFKA_SASL_MECHANISM:PLAIN}
      sasl.jaas.config: ${KAFKA_SASL_JAAS_CONFIG:}
    consumer:
      group-id: ${KAFKA_GROUP_ID:top-5g-pm-file-sync}
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      auto-offset-reset: ${KAFKA_AUTO_OFFSET_RESET:latest}
    listener:
      ack-mode: ${KAFKA_LISTENER_ACK_MODE:batch}
      missing-topics-fatal: false

logging:
  level:
    root: ${LOG_LEVEL:INFO}
  file:
    name: ${LOG_FILE_PATH:logs/top-5g-pm-file-sync.log}

app:
  kafka:
    topic: ${KAFKA_TOPIC:top.5g.pm.files} 